{% set name = "jep" %}
{% set version = "4.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 33336f6afc37e1a4888586a2f0017ac01e2093891640ce1b41cbbf35f4317a9f

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [not linux]
  missing_dso_whitelist:
    # jep uses LD_PRELOAD to set the correct path to libjvm.so at runtime.
    - '*/libjvm.so'

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - pip
    - python
    - openjdk ==8.*
    - setuptools
    - numpy
  run:
    - python
    - openjdk ==8.*

test:
  commands:
    - jep test.py
  files:
    - test.py

about:
  home: https://github.com/ninia/jep
  license: Zlib
  license_file: LICENSE
  summary: Jep embeds CPython in Java
  dev_url: https://github.com/ninia/jep

extra:
  recipe-maintainers:
    - CJ-Wright
