{% set name = "jep" %}
{% set version = "4.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5914a4d815a7e86819f55be3de840edc2d3fe0d0b3f67626e5cea73841b1d1c0

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [not linux]
  missing_dso_whitelist:
    # jep uses LD_PRELOAD to set the correct path to libjvm.so at runtime.
    - '*/libjvm.so'

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - openjdk ==8.*
    - numpy
  run:
    - python
    - openjdk ==8.*
    - {{ pin_compatible('numpy') }}

test:
  commands:
    - jep test.py
  files:
    - test.py

about:
  home: https://github.com/ninia/jep
  license: Zlib
  license_file: LICENSE
  summary: Jep embeds CPython in Java
  dev_url: https://github.com/ninia/jep

extra:
  recipe-maintainers:
    - CJ-Wright
