{% set name = "jep" %}
{% set version = "4.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4deb6f9f5bc993a0818861efc5323ccc71373c4c38f303fc412998f02dde6e5c

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [not linux]
  missing_dso_whitelist:
    # jep uses LD_PRELOAD to set the correct path to libjvm.so at runtime.
    - '*/libjvm.so'

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - pip
    - python
    - openjdk ==8.*
    - setuptools
    - numpy
  run:
    - python
    - openjdk ==8.*

test:
  commands:
    - jep test.py
  files:
    - test.py

about:
  home: https://github.com/ninia/jep
  license: Zlib
  license_file: LICENSE
  summary: Jep embeds CPython in Java
  dev_url: https://github.com/ninia/jep

extra:
  recipe-maintainers:
    - CJ-Wright
