{% set name = "jep" %}
{% set version = "4.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8984acd9e2424dcb1325020e43b4bb7b67e1cf4b9011f1bee7a3f4130a344907

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [not linux]
  missing_dso_whitelist:
    # jep uses LD_PRELOAD to set the correct path to libjvm.so at runtime.
    - '*/libjvm.so'

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - pip
    - python
    - openjdk ==8.*
    - numpy
  run:
    - python
    - openjdk ==8.*
    - {{ pin_compatible('numpy') }}

test:
  commands:
    - jep test.py
  files:
    - test.py

about:
  home: https://github.com/ninia/jep
  license: Zlib
  license_file: LICENSE
  summary: Jep embeds CPython in Java
  dev_url: https://github.com/ninia/jep

extra:
  recipe-maintainers:
    - CJ-Wright
